# Generated by Django 4.0.2 on 2022-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desciption', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(upload_to='static/course/thumbnail')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resources', models.FileField(upload_to='static/course/resources')),
                ('hours', models.IntegerField()),
                ('chapter', models.IntegerField()),
            ],
        ),
    ]
