# Generated by Django 4.0.2 on 2022-02-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
