# Generated by Django 4.0.2 on 2022-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_payment_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
