# Generated by Django 4.0.2 on 2022-03-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_couponcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
