# Generated by Django 4.0.1 on 2022-02-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='imges',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
