# Generated by Django 4.0.1 on 2022-02-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_imges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='imges',
        ),
    ]
